### ISSUE TITLE
Unable to resize window below a certain value

### ISSUE THREAD

**Issue by raniesantos** [rvpanoz/luna#105]
**Describe the bug**
Unable to resize window below a certain value.

**To Reproduce**
N/A

**Expected behavior**
I should be able to resize the window freely.

**Screenshots**
![screenshot from 2018-09-01 01-24-37](https://user-images.githubusercontent.com/8528269/44927197-2ef79300-ad86-11e8-8fdd-8e3290e57284.png)

**Desktop:**
 - OS: Linux Mint 18.1
- 1366x768 resolution

**Additional context**
N/A

**Comment by raniesantos** [comment]
Please make the minimum window height lower. Probably around 650px.

**Comment by rvpanoz** [comment]
OK, I will try to fix it next week :)

**Comment by raniesantos** [comment]
Closing because I stopped using the app.
