### ISSUE TITLE
Why only the sources in the release?

### ISSUE THREAD

**Issue by foxdog05000** [rvpanoz/luna#29]
Hello, why in the release section: only the sources are included. Why not add packaged versions of the app for Windows, Linux and Mac OS ?

**Comment by rvpanoz** [comment]
Hello foxdog, 

The application is available for Linux and Windows based systems. 
About the releases section you are correct, I forgot to add the packaged versions. :-1: 

Thanks for adding the issue. If you have any other comments or issues, even enchancements I will be glad to help you.

**Comment by foxdog05000** [comment]
Thank you, thank you also for your work 👍

**Comment by rvpanoz** [comment]
I have updated the releases section. If you need any help or have a problem with the app dont hesitate to contact me.

Thanks again for your comment.
