### ISSUE TITLE
Luna not full responsive ?

### ISSUE THREAD

**Issue by foxdog05000** [rvpanoz/luna#30]
Hello, I really appreciate your work! This application saves a lot of time, thank you.
I use your application on my two PCs (one fixed and one laptop). I have no problem on my desktop PC with 1920x1080 screen.

On the other hand, I have a problem with your application: using it from my laptop that displays 1366x768. The problem is that I'm missing the right part of the application in order to update or uninstall a module. So I ask myself the question of the responsive of your application? (Screenshot below)

![image](https://user-images.githubusercontent.com/18735549/33345985-69d4e44a-d48e-11e7-95c9-5a0997ee3312.png)

**Comment by rvpanoz** [comment]
Hello again :)

The application has a responsive design. 
Maybe some custom css rules broke the design in small screens.

I will fix it asap.
