### ISSUE TITLE
No REMOVE command in Luna

### ISSUE THREAD

**Issue by aplatypus** [rvpanoz/luna#34]
> Expected behavior and actual behavior.

- I wanted to `remove` a package from the local `npm` repository
- I expected to find a `remove` action ... Somewhere

> Actual behaviour.

- No Action was found.
- If there is a menu or action some place, it is very well disguised

> Steps to reproduce the problem.

- Install some package.
- Example: `min` database (quite small)
- Select that package.
- Try to `remove` it

> Workaround

- Go to cmd window (command line shell)
```
  npm remove min   
rem   OR ...
  npm remove min -g
```
- `min' was installed as global

> Specifications like operating system, or hardware

Windows 10 64-bit

**Comment by rvpanoz** [comment]
Hey aplatypus,

I believe that when saying remove you mean uninstall?
If so, in the package details there is an option menu (top right corner) where you can uninstall the package. 

Hope that helps
