### ISSUE TITLE
Remove Numix Branding

### ISSUE THREAD

**Issue by Foggalong** [rvpanoz/luna#35]
At first I thought it was just a coincidence that the logo looked similar to the Numix Project one but after downloading the file to check it would seem that they're identical binaries. While we do release a GPL version of our logo for use in icon themes, the version you've used isn't licensed as such and so your software as is is in violation of the GPL. Aside from that it's just confusing branding wise; it implies affiliation between the two when this isn't the case.

Please remove all Numix branding from your software. If you want help drafting up a new icon I'm more than happy to help out, but as is it's not really fair (nor strictly speaking legal) to take our logo and put it on your software.

**Comment by rvpanoz** [comment]
Hello Foggalong, I did not know that the Icon is your branding logo. I will remove it today. 

Have a nice day :)
