### ISSUE TITLE
install packages from package.json

### ISSUE THREAD

**Issue by Suleman-Elahi** [rvpanoz/luna#36]
Is it possible in this tool to install all the packages in one shot after analyzing them from the "package.json" file. And also for the update operation.

**Comment by rvpanoz** [comment]
Hello Suleman,

In this version you cant.. but I am working a new version based on material-ui with many new features like the one you mentioned

**Comment by rvpanoz** [comment]
#58f61ead0781288110cb22f63d67efcd40312205
