### ISSUE TITLE
macOS version

### ISSUE THREAD

**Issue by erikjara** [rvpanoz/luna#38]
We will get macOS version in the future? thanks!

**Comment by rvpanoz** [comment]
Hey erikjara,

Yes, I am preparing some major updates in the near future. Stay tuned :1st_place_medal:

**Comment by erikjara** [comment]
Do you need help with somebody?
![captura de pantalla 2018-04-12 a la s 09 31 13](https://user-images.githubusercontent.com/29052553/38677676-55abda80-3e35-11e8-8986-fead6793f5fe.png)

At least works fine in MacOS 10.13.4

**Comment by rvpanoz** [comment]
Hey erik, 

Yes, I need someone to run the build command `npm run package-all` on mac and upload the binary.  As I see from the image you run the app in dev mode `npm run dev`.  I have talked @madsnedergaard and he will make the build. If I need extra help.. may I contact you?

I hope you find luna useful. Feel free to suggest improvements or make a PR 

Thanks for your time to make the comment.
