### ISSUE TITLE
pnpm support

### ISSUE THREAD

**Issue by skayo** [rvpanoz/luna#450]
Hey!  
I'll just use the format from the template:

**Is your feature request related to a problem? Please describe.**
pnpm uses hard links and symlinks to save one version of a module only ever once on a disk. When using npm or Yarn for example, if you have 100 projects using the same version of lodash, you will have 100 copies of lodash on disk. With pnpm, lodash will be saved in a single place on the disk and a hard link will put it into the `node_modules` where it should be installed.
As a result, you save gigabytes of space on your disk and you have a lot faster installations!
And because luna is using npm only, it's unusable for me and other people that mainly use pnpm.

**Describe the solution you'd like**
According to the [pnpm documentation](https://pnpm.js.org/en/pnpm-cli), you can just use `pnpm` instead of `npm`. So you'd just have to use `pnpm` everywhere in the code, if enabled.

**Additional context**
I've made this feature request as requested in #96.
Also I can definitely recommend you to just try out pnpm by yourself! It's super useful in my opinion!

**Comment by rvpanoz** [comment]
I have started working on pnpm and yarn support
