### ISSUE TITLE
not run in macos

### ISSUE THREAD

**Issue by mehdiraized** [rvpanoz/luna#453]
**Bug description**
open application and see this error
![Screen Shot 2020-04-25 at 21 20 12](https://user-images.githubusercontent.com/4368004/80285511-c28b8d80-873a-11ea-92fe-604946f85625.png)

**Desktop**
 - OS: MacOS
 - Version 10.15.4

**Comment by rvpanoz** [comment]
I will take a look. Thank you for your comment.

**Comment by benjamin79** [comment]
Any update?

**Comment by rvpanoz** [comment]
hey! yes I managed to solve it. I will updare the repo soon. Sorry for the delay.

**Comment by rvpanoz** [comment]
fixed in #483
