### ISSUE TITLE
Window height problem in Linux

### ISSUE THREAD

**Issue by aerfanr** [rvpanoz/luna#463]
**Bug description**
The minimum window height is too much in Linux. The bottom of the window (including page navigation buttons) is not visible.
Also, there is too much empty space at the bottom of the screen.

**To Reproduce**
1. Run the program.
2. Observe the bug.
3. Maximize the program.
4. Observe the bug again.

**Expected behavior**
I think the empty space at the bottom of the page should be reduced. The minimum window height should be reduced. And packages count on a page (currently 10) should be reduced in some cases.

**Screenshots**
**Maximized window:**
![Screenshot_20200827_221119](https://user-images.githubusercontent.com/22169659/91476494-51a7de00-e8b2-11ea-8ecc-ebe9c5557805.png)
**Moved window (so the bottom is visible):**
![Screenshot_20200827_221310](https://user-images.githubusercontent.com/22169659/91476643-81ef7c80-e8b2-11ea-934c-01ed1d6fa235.png)
**Maximized in a smaller screen:**
![image](https://user-images.githubusercontent.com/22169659/91476762-ab100d00-e8b2-11ea-84d9-60fd57ba6c94.png)

**Desktop**
 - OS: Linux
 - Version: Fedora 32 
I use Linux with KDE Plasma desktop. I have a panel at the top of my screen (I think it is related).
 - KDE Plasma Version: 5.18

**Comment by rvpanoz** [comment]
fixed in [3.3.5 release](https://github.com/rvpanoz/luna/releases/tag/3.3.5)
