### ISSUE TITLE
first run contains a few errors / 2 request

### ISSUE THREAD

**Issue by solitarymx** [rvpanoz/luna#464]
1 - Empty screen in first run.
a ) I'm wait 5+ min but, nothing. Only showing spinner in main window.
b ) Notification badge show "9" but click and nothing.
c ) Settings button not have hint. There's no explanation when it comes to it.

2 - Creating desktop shortcut incorrectly.
d ) When I turn on properties, the target area is empty and unediable(read only).
e ) "Open file location" button disable (read only)
f ) "Change icon" button disable.
g ) Therefore, the "run as administrator" option is not available in the menu.

3 - Resolution is not stable.
h ) Close to the top left of the screen, When I grab it from the title bar and drag it to the center of the screen, its width and height change (it grows).

4 - Settings section does not work.
i ) Settings button click and open settings screen but all "change buttons" disabled.

5 - npm and luna different show result.
j ) The global package partition shows the same as the installed and recentl released package, like cool
but when cmd.exe runs the following command, "npm outdated" shows a different table. it doesn't work healthily.
-> Oh, okay, I see why that's the way it is. Because Luna automatically takes the "AppData" folder, but I keep my global packages on another drive.

6 - Back to package button disabled.
k ) After opening a project, it is required to exit and reopen the program to return to global packages.

Request:
Request for listing operations.
1 ) List is limited 10 records, It would be nice if at least "show them all" could be added to it. (ex: 1 scroll list show all packages, or no paginations)
2 ) it is really white all screen :( please add gray-dark blue or black background.
that is, it would be great if something like (dark mode) could be added.

Here's what I did during the second run.
1. Delete desktop shortcut. open "C:\Users\user\AppData\Local\Programs\luna" and send desktop shortcut.
2. New shortcut "run as administrator"
steps 3-4-5 and 6 continue.

Here's what I did during the third and other run.
2. New shortcut "run as administrator"
steps 3-4-5 and 6 continue.

 - OS: Windows 10 x64
 - Version 3.3.0-stable

I know it's been a long time, i hope you can evaluate it.
Thank you, good work.

**Comment by rvpanoz** [comment]
Woohoo! Thanks for that. I am working on a new design these days. Trying to find time to finish it..Really appreciate your feedback. I will do my best.

**Comment by rvpanoz** [comment]
[release 3.3.5](https://github.com/rvpanoz/luna/releases/tag/3.3.5) with some fixes.

**Comment by solitarymx** [comment]
Thank you, I'll load it up and check it out in a few days.
I wish you good work.

**Comment by rvpanoz** [comment]
cool there is no rush. Meanwhile I will keep pushing updates :wink:

**Comment by rvpanoz** [comment]
I close it as many of the issues are sorted. Dark mode will be available on next releases.
