### ISSUE TITLE
Weird little bug installing dependencies on windows

### ISSUE THREAD

**Issue by Fraasi** [rvpanoz/luna#51]
Probably nothing to be concerned about, but after 
`git clone` & `npm i`, running `npm run dev` resulted in "'cross-env' is not recognized as an internal or external command", even though package.json listed it and I assume it was installed with all the rest. After checking out what it is and running `npm install --save-dev cross-env` as a first aid, everything works although there are some unrelated errors in console.  
I have no idea what the "npm ERR! code EBADPLATFORM" is and is it related, but the whole thing works beautifully and looks nice.  
Also I'm a ittle flabbergasted by the 1740(!) packages cross-env updated.  

win 10  
node v8.9.4  
npm  v5.6.0

Screenshot of my little adventure.
![2018-04-15_1127](https://user-images.githubusercontent.com/22402899/38777378-7e373496-40af-11e8-843b-4e1cddfc8a1b.png)

**Comment by rvpanoz** [comment]
Hello Frassi, could you post the npm log related to this error? Maybe we find something in there.

**Comment by Fraasi** [comment]
Sure. Here you go:
[2018-04-15T07_38_08_993Z-debug.zip](https://github.com/rvpanoz/luna/files/1912384/2018-04-15T07_38_08_993Z-debug.zip)
[2018-04-15T07_49_10_702Z-debug.zip](https://github.com/rvpanoz/luna/files/1912391/2018-04-15T07_49_10_702Z-debug.zip)  
There was two logs mentioned in above screenshot and the first one is rather looong, so hope this zipped delivery is ok.

**Comment by rvpanoz** [comment]
OK, something happening with the app-builder-mac package. I am investigating it. 
Btw the application is running without issues?

**Comment by rvpanoz** [comment]
I had to remove app-builder dependency because is not need.. electron-builder do the job.
Try to make a new install and you will be fine :)

(remove the node_modules folder and `npm i`

**Comment by madsnedergaard** [comment]
That's weird, I don't see why cross-env would have a problem with this package - I'll try to see if I can get the build going without it :)

**Comment by rvpanoz** [comment]
yes its weird, but as I can see from the logs app-builder cannot install on
windows! :lol
check the npm logs files that he sent me

**Comment by rvpanoz** [comment]
If you have time.. no worries :)

**Comment by Fraasi** [comment]
Woops :) I thought maybe this is just a little glitch in my matrix machine, but apparently there is a bug to be squashed.  
> By the way, the application is running without issues? Does the executable run on your machine?  

I only tried it git cloned & npm'd, but after installing cross-env separately as I mentioned in the first post, yes, it worked totally fine, I removed & updated some of my global packages and everything went smoothly.

**Comment by rvpanoz** [comment]
Yes it seems that we have a bug.. but we will fix it soon. :1234: 
I am glad that the application is working.

**Comment by rvpanoz** [comment]
app-builder-bin-mac is an optional dependency. So on windows it want install. 
package.json updated.
