### ISSUE TITLE
npm latest version displayed is wrong

### ISSUE THREAD

**Issue by GHNewbiee** [rvpanoz/luna#521]
**Bug description**
`npm` installed version is *7.0.3* but the latest one that `luna` displays is *6.14.8*.

**To Reproduce**
Just install the latest `deb` package: *luna_3.3.5_amd64.deb*

**Expected behavior**
To find the correct latest version of `npm` package which is *7.0.5* or at least *7.0.4*.

**Screenshots**
![luna](https://user-images.githubusercontent.com/26875662/97300648-09c41980-1857-11eb-9aa9-3a897cb203c4.png)
![luna-2](https://user-images.githubusercontent.com/26875662/97302073-d97d7a80-1858-11eb-9733-b4f0143b096b.png)

**Desktop**
 - OS: LinuxMint
 - Version: 20

**Additional context**
None

**Comment by rvpanoz** [comment]
Hey @GHNewbiee! Thank you for your comment. 

Could you please install the latest version and tell me if the error still occurs? 
[v.3.4.5](https://github.com/rvpanoz/luna/releases/tag/v3.4.5)

**Comment by GHNewbiee** [comment]
Yes, unfortunately, the error does still occur.

**Comment by rvpanoz** [comment]
ok I will try to reproduce it then. I will keep you updated.

**Comment by GHNewbiee** [comment]
Just keep in mind that [`npm`](https://www.npmjs.com/package/npm) shows the old version `6.14.8` different than that in [@npm/cli](https://github.com/npm/cli). I suspect you retrieve package info by two different ways.

**Comment by rvpanoz** [comment]
Hey! Are you using `nvm`? Luna uses `npm list -g --json --depth=0` and `npm outdated -g --json --depth=0` commands to get the packages and outdated packages. Could you please run `npm outdated -g --json --depth=0` at the terminal and check what is the output?

**Comment by GHNewbiee** [comment]
Hi!
- No, I do not use nvm.
- `npm list -g --json --depth=0` output
```json
{
  "dependencies": {
    "csso-cli": {
      "version": "3.0.0",
      "resolved": "https://registry.npmjs.org/csso-cli/-/csso-cli-3.0.0.tgz"
    },
    "degit": {
      "version": "2.8.0",
      "resolved": "https://registry.npmjs.org/degit/-/degit-2.8.0.tgz"
    },
    "express-gateway": {
      "version": "1.16.10",
      "resolved": "https://registry.npmjs.org/express-gateway/-/express-gateway-1.16.10.tgz"
    },
    "fkill-cli": {
      "version": "6.0.1",
      "resolved": "https://registry.npmjs.org/fkill-cli/-/fkill-cli-6.0.1.tgz"
    },
    "generator-open-wc": {
      "version": "0.7.3",
      "resolved": "https://registry.npmjs.org/generator-open-wc/-/generator-open-wc-0.7.3.tgz"
    },
    "moleculer-cli": {
      "version": "0.7.1",
      "resolved": "https://registry.npmjs.org/moleculer-cli/-/moleculer-cli-0.7.1.tgz"
    },
    "moleculer-repl": {
      "version": "0.6.4",
      "resolved": "https://registry.npmjs.org/moleculer-repl/-/moleculer-repl-0.6.4.tgz"
    },
    "npm-check-updates": {
      "version": "9.2.3"
    },
    "npm-check": {
      "version": "5.9.2",
      "resolved": "https://registry.npmjs.org/npm-check/-/npm-check-5.9.2.tgz"
    },
    "npm-install-peers": {
      "version": "1.2.1",
      "resolved": "https://registry.npmjs.org/npm-install-peers/-/npm-install-peers-1.2.1.tgz"
    },
    "npm": {
      "version": "7.0.3"
    },
    "pm2": {
      "version": "4.5.0",
      "resolved": "https://registry.npmjs.org/pm2/-/pm2-4.5.0.tgz"
    },
    "web-component-analyzer": {
      "version": "1.1.6",
      "resolved": "https://registry.npmjs.org/web-component-analyzer/-/web-component-analyzer-1.1.6.tgz"
    },
    "yo": {
      "version": "3.1.1",
      "resolved": "https://registry.npmjs.org/yo/-/yo-3.1.1.tgz"
    }
  }
}
 ```
- `npm outdated -g --json --depth=0` output
```json
{
  "npm": {
    "current": "7.0.3",
    "wanted": "6.14.8",
    "latest": "6.14.8",
    "dependent": "global",
    "location": "/usr/lib/node_modules/npm"
  }
}

```
But I use `sudo npm-check -gu`
```bash
$ sudo npm-check -gu
The global path you are searching is: /usr/lib/node_modules
❤️  Your modules look amazing. Keep up the great work. ❤️
```
and `npm-check-updates`
```bash
$ npm-check-updates -g
[====================] 14/14 100%

All global packages are up-to-date :)
```
- finally
```bash
$ node -v
v15.0.1
```
Q1: Which method/package do you use to get the package versions?

**Comment by rvpanoz** [comment]
I am not using any package or a custom method to get the versions. I am using npm list and outdated commands and parsing the output.

**Comment by rvpanoz** [comment]
Note that npm v.7.x.x is a development release and thats why is not listed as LTS release

**Comment by GHNewbiee** [comment]
So, it has to do with `npm` **weird** concepts. *Thanks for your time!*
