### ISSUE TITLE
The horizontal date axis under the Statistics tab can get crowded and hard to read

### ISSUE THREAD

**Issue by BehindTheMath** [rvpanoz/luna#55]
> Expected behavior and actual behavior.

The horizontal date axis under Github stats on the Statistics tab can get crowded and hard to read

![image](https://user-images.githubusercontent.com/9314934/38825207-b983030c-4179-11e8-98eb-5f3998c3822e.png)

> Specifications like operating system, or hardware

Windows 10 x64

Luna 2.1.0

**Comment by rvpanoz** [comment]
Fix #66

**Comment by rvpanoz** [comment]
Fix #66
