### ISSUE TITLE
[Feature Suggestion] Add clickable links

### ISSUE THREAD

**Issue by BehindTheMath** [rvpanoz/luna#61]
There is a lot of data that could be made into links:
* Under Github stats, the dependencies could be links to open that package in Luna.
* Under Github stats, the Dist Tags could be links to preview that version.
* The usernames, emails, and URLs under Details, Maintainers, and Contributors.
* The license.

> Specifications like operating system, or hardware

Windows 10 x64

Luna 2.1.0

**Comment by rvpanoz** [comment]
fix #69
