### ISSUE TITLE
After viewing a package that was searched for, the Show Globals button doesn't work

### ISSUE THREAD

**Issue by BehindTheMath** [rvpanoz/luna#65]
> Expected behavior and actual behavior.

The Show Globals button should always show to the list of global packages.

However, after viewing a package that was searched for, the Show Globals button doesn't do anything.

> Steps to reproduce the problem.

1. Search for a package, and click one of the results to view it.
2. Click the Show Globals button. Nothing will happen.

> Specifications like operating system, or hardware

Windows 10 x64

Luna 2.1.0

**Comment by rvpanoz** [comment]
Hello, hope you are well

I can not reproduce the bug you mention. I search for a package, then preview the details of that package (click on package). The Show globals buttons is working correctly.

**Comment by rvpanoz** [comment]
fix #69
