### ISSUE TITLE
When removing a package, all packages are reloaded

### ISSUE THREAD

**Issue by mAAdhaTTah** [rvpanoz/luna#67]
> Expected behavior and actual behavior.

Actual: When I click the check box next to a global npm package and click the trash can to get rid of it, Luna reloads the entire list of packages. I currently have 98 packages, and want to clear some of them out, and reloading every time I remove one slows down this process considerably.

Expected: Luna can / should optimistically remove the package from its list and reload the list from disk in the background.

> Specifications like operating system, or hardware

I'm on a MBP w/ 16GBs of RAM & 2.5GHz processor.

**Comment by rvpanoz** [comment]
Hello mAAdhaTTah,

I am preparing an update so I will include your suggestion too.
