### ISSUE TITLE
unable to quit on macOS Darwin

### ISSUE THREAD

**Issue by ilyaztsv** [rvpanoz/luna#78]
> Expected behavior and actual behavior.

Expected: `Quit` closes the app
Actual: `Quit` does not close the app

> Steps to reproduce the problem.

- Launch `luna`
- right click on app icon
- Quit 

See GIF: https://www.dropbox.com/s/0xwv3n4sz2nf2fj/luna-macos-quit.gif?dl=0

> Specifications like operating system, or hardware

```
System Software Overview:

      System Version: macOS 10.13.4 (17E202)
      Kernel Version: Darwin 17.5.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
```

```
luna version: 2.1.0
```

**Comment by rvpanoz** [comment]
ok I will check it soon
