### ISSUE TITLE
Wrong screen size in Retina screens

### ISSUE THREAD

**Issue by chinesedfan** [rvpanoz/luna#91]
> Expected behavior and actual behavior.

After I clicked the app icon, nothing is there. I try to debug with the terminal and find,

```
[zhong@localhost picasso-debugger]$ node node_modules/.bin/electron /Applications/luna.app/Contents/Resources/app.asar 
(node:69768) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Fatal: LOW_RESOLUTION
```

I use 2560x1600 Retina screen, but `getPrimaryDisplay().size` only returns `1280x800`. Maybe we should consider `display.scaleFactor` and give a better warning for low resolution users.

> Steps to reproduce the problem.

Download and try to launch `luna@2.1.1`.

> Specifications like operating system, or hardware

Mac OSX. 2560 x 1600 Retina screen.

**Comment by rvpanoz** [comment]
Ok I need your help with this. How we can use the display.scaleFactor? or maybe remove this functionality? We can collaborate on this.

**Comment by chinesedfan** [comment]
Ha, I am not an Electron expert. I am learning to build Electron apps and find here. :)

Why did you add this functionality at the beginning? Was it because the UI would become weird with low screen resolution? If not, I suggest to removing this functionality.

**Comment by rvpanoz** [comment]
ok I will investigate it at the weekend. Maybe this check is useless code and may be removed. :grinning:
